-file("/usr/local/lib/erlang/lib/parsetools-2.0.9/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(test).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/test.xrl", 152).

make_token(Name, Line, Chars) when is_list(Chars) ->
    {token, {Name, Line, list_to_atom(Chars)}};
make_token(Name, Line, Chars) ->
    {token, {Name, Line, Chars}}.

make_token(Name, Line, Chars, Fun) ->
    {token, {Name, Line, Fun(Chars)}}.

endls(Chars) ->
    lists:filter(fun (C) -> C == $\n orelse C == $; end, Chars).

atom_or_identifier(String, TokenLine) ->
     case is_reserved(String) of
         true ->
            {list_to_atom(String), TokenLine};
         false ->
            {atom, TokenLine, build_atom(String, TokenLine)}
     end.

bin_to_integer("0b" ++ Number) ->
    {ok, [Val], _} = io_lib:fread("~2u", Number),
    Val.

oct_to_integer("0o" ++ Number) ->
    {ok, [Val], _} = io_lib:fread("~8u", Number),
    Val.

hex_to_integer("0x" ++ Number) ->
    {ok, [Val], _} = io_lib:fread("~16u", Number),
    Val.

is_reserved("if")      -> true;
is_reserved("else")    -> true;
is_reserved("try")     -> true;
is_reserved("catch")   -> true;
is_reserved("receive") -> true;
is_reserved("after")   -> true;
is_reserved("case")    -> true;
is_reserved("switch")  -> true;
is_reserved("when")    -> true;
is_reserved("fn")      -> true;
is_reserved("do")      -> true;
is_reserved("for")     -> true;
is_reserved("in")      -> true;
is_reserved("begin")   -> true;
is_reserved(_)         -> false.

build_string(Type, Chars, Line, Len) ->
  String = unescape_string(lists:sublist(Chars, 2, Len - 2), Line),
    {token, {Type, Line, String}}.

unescape_string(String, Line) -> unescape_string(String, Line, []).

unescape_string([], _Line, Output) ->
  lists:reverse(Output);
unescape_string([$\\, Escaped | Rest], Line, Output) ->
  Char = map_escaped_char(Escaped, Line),
  unescape_string(Rest, Line, [Char|Output]);
unescape_string([Char|Rest], Line, Output) ->
  unescape_string(Rest, Line, [Char|Output]).

map_escaped_char(Escaped, Line) ->
  case Escaped of
    $\\ -> $\\;
    $/ -> $/;
    $\" -> $\";
    $\' -> $\';
    $\( -> $(;
    $b -> $\b;
    $d -> $\d;
    $e -> $\e;
    $f -> $\f;
    $n -> $\n;
    $r -> $\r;
    $s -> $\s;
    $t -> $\t;
    $v -> $\v;
    _ -> throw({error, {Line, fn_lexer, ["unrecognized escape sequence: ", [$\\, Escaped]]}})
  end.

list_to_charnum([_, $\\, Char], Line) ->
  map_escaped_char(Char, Line);
list_to_charnum([_, Char], _Line) -> Char.

build_atom([$'|_] = Atom, Line) ->
    list_to_atom(unescape_string(lists:sublist(Atom, 2, length(Atom) - 2), Line));
build_atom(Atom, _Line) -> list_to_atom(Atom).
-file("/usr/local/lib/erlang/lib/parsetools-2.0.9/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L1, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L1, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L1, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/test.erl", 364).
yystate() -> 99.

yystate(106, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(105, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(105, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,105};
yystate(104, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(103, [59|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line, Tlen+1, 53, Tlen);
yystate(103, [35|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 53, Tlen);
yystate(103, [32|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 53, Tlen);
yystate(103, [13|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 53, Tlen);
yystate(103, [10|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line+1, Tlen+1, 53, Tlen);
yystate(103, [9|Ics], Line, Tlen, _, _) ->
    yystate(103, Ics, Line, Tlen+1, 53, Tlen);
yystate(103, Ics, Line, Tlen, _, _) ->
    {53,Tlen,Ics,Line,103};
yystate(102, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(102, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(94, Ics, Line, Tlen+1, Action, Alen);
yystate(102, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(102, Ics, Line+1, Tlen+1, Action, Alen);
yystate(102, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(102, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(102, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(102, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(102, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,102};
yystate(101, [46|Ics], Line, Tlen, _, _) ->
    yystate(105, Ics, Line, Tlen+1, 17, Tlen);
yystate(101, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Tlen+1, 17, Tlen);
yystate(101, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,101};
yystate(100, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 7, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 7, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 7, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 7, Tlen);
yystate(100, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,100};
yystate(99, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [121|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [122|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [120|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(106, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(98, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [63|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(96, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(104, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(96, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line+1, Tlen+1, Action, Alen);
yystate(99, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(101, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [C|Ics], Line, Tlen, Action, Alen) when C >= 98, C =< 101 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 109 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [C|Ics], Line, Tlen, Action, Alen) when C >= 112, C =< 115 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(99, [C|Ics], Line, Tlen, Action, Alen) when C >= 117, C =< 119 ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(99, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,99};
yystate(98, [62|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 30, Tlen);
yystate(98, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line,98};
yystate(97, [101|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line, Tlen+1, 16, Tlen);
yystate(97, [69|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line, Tlen+1, 16, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(97, Ics, Line, Tlen+1, 16, Tlen);
yystate(97, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,97};
yystate(96, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(95, [59|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line, Tlen+1, 51, Tlen);
yystate(95, [35|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 51, Tlen);
yystate(95, [32|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 51, Tlen);
yystate(95, [13|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 51, Tlen);
yystate(95, [10|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line+1, Tlen+1, 51, Tlen);
yystate(95, [9|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 51, Tlen);
yystate(95, Ics, Line, Tlen, _, _) ->
    {51,Tlen,Ics,Line,95};
yystate(94, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line};
yystate(93, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line};
yystate(92, [100|Ics], Line, Tlen, _, _) ->
    yystate(100, Ics, Line, Tlen+1, 6, Tlen);
yystate(92, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 6, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 6, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 6, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(27, Ics, Line, Tlen+1, 6, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 6, Tlen);
yystate(92, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,92};
yystate(91, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(90, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(89, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(89, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(89, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,89};
yystate(88, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 39 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 41, C =< 64 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 123 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(88, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,88};
yystate(87, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line+1, Tlen+1, Action, Alen);
yystate(87, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,87};
yystate(86, [92|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 48, Tlen);
yystate(86, [39|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 48, Tlen);
yystate(86, [10|Ics], Line, Tlen, _, _) ->
    yystate(102, Ics, Line+1, Tlen+1, 48, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(102, Ics, Line, Tlen+1, 48, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(102, Ics, Line, Tlen+1, 48, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(102, Ics, Line, Tlen+1, 48, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(102, Ics, Line, Tlen+1, 48, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,86};
yystate(85, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(84, [100|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 48, Tlen);
yystate(84, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(84, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,84};
yystate(83, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(82, [124|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 29, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,82};
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(81, Ics, Line, Tlen+1, 16, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,81};
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(44, Ics, Line, Tlen+1, 45, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 11 ->
    yystate(44, Ics, Line, Tlen+1, 45, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {45,Tlen,Ics,Line,80};
yystate(79, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line+1, Tlen+1, Action, Alen);
yystate(79, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,79};
yystate(78, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(78, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(78, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(78, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Tlen+1, Action, Alen);
yystate(78, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(102, Ics, Line+1, Tlen+1, Action, Alen);
yystate(78, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(78, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(78, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(78, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(78, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,78};
yystate(77, [61|Ics], Line, Tlen, _, _) ->
    yystate(85, Ics, Line, Tlen+1, 36, Tlen);
yystate(77, [58|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 36, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,77};
yystate(76, [110|Ics], Line, Tlen, _, _) ->
    yystate(84, Ics, Line, Tlen+1, 48, Tlen);
yystate(76, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(76, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,76};
yystate(75, [93|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 3, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,75};
yystate(74, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(73, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,73};
yystate(72, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(71, [59|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line, Tlen+1, 52, Tlen);
yystate(71, [35|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 52, Tlen);
yystate(71, [32|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 52, Tlen);
yystate(71, [13|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 52, Tlen);
yystate(71, [10|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line+1, Tlen+1, 52, Tlen);
yystate(71, [9|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 52, Tlen);
yystate(71, Ics, Line, Tlen, _, _) ->
    {52,Tlen,Ics,Line,71};
yystate(70, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(102, Ics, Line+1, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(70, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,70};
yystate(69, [120|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 17, Tlen);
yystate(69, [111|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 17, Tlen);
yystate(69, [98|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 17, Tlen);
yystate(69, [46|Ics], Line, Tlen, _, _) ->
    yystate(105, Ics, Line, Tlen+1, 17, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Tlen+1, 17, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,69};
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 45, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(60, Ics, Line, Tlen+1, 45, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(60, Ics, Line, Tlen+1, 45, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(60, Ics, Line, Tlen+1, 45, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {45,Tlen,Ics,Line,68};
yystate(67, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line};
yystate(66, [95|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 46, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(66, Ics, Line, Tlen+1, 46, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(66, Ics, Line, Tlen+1, 46, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(66, Ics, Line, Tlen+1, 46, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {46,Tlen,Ics,Line,66};
yystate(65, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line+1, Tlen+1, Action, Alen);
yystate(65, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(65, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,65};
yystate(64, [115|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 48, Tlen);
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,64};
yystate(63, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(62, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(61, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,61};
yystate(60, [95|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 44, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(60, Ics, Line, Tlen+1, 44, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(60, Ics, Line, Tlen+1, 44, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(60, Ics, Line, Tlen+1, 44, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {44,Tlen,Ics,Line,60};
yystate(59, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(58, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,58};
yystate(57, [59|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 51, Tlen);
yystate(57, [35|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 51, Tlen);
yystate(57, [33|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 51, Tlen);
yystate(57, [34|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 51, Tlen);
yystate(57, [32|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 51, Tlen);
yystate(57, [13|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 51, Tlen);
yystate(57, [11|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 51, Tlen);
yystate(57, [12|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 51, Tlen);
yystate(57, [10|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line+1, Tlen+1, 51, Tlen);
yystate(57, [9|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 51, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(49, Ics, Line, Tlen+1, 51, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(49, Ics, Line, Tlen+1, 51, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 58 ->
    yystate(49, Ics, Line, Tlen+1, 51, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 60 ->
    yystate(49, Ics, Line, Tlen+1, 51, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {51,Tlen,Ics,Line,57};
yystate(56, [108|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 48, Tlen);
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,56};
yystate(55, [61|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 14, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,55};
yystate(54, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(53, Ics, Line, Tlen+1, 20, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(53, Ics, Line, Tlen+1, 20, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(53, Ics, Line, Tlen+1, 20, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,53};
yystate(52, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(51, [111|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 48, Tlen);
yystate(51, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,51};
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 50, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, 50, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(50, Ics, Line, Tlen+1, 50, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(50, Ics, Line, Tlen+1, 50, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {50,Tlen,Ics,Line,50};
yystate(49, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line+1, Tlen+1, Action, Alen);
yystate(49, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 8 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 31 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 36, C =< 58 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, [C|Ics], Line, Tlen, Action, Alen) when C >= 60 ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(49, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,49};
yystate(48, [97|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 48, Tlen);
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,48};
yystate(47, [61|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 34, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,47};
yystate(46, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 55 ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,45};
yystate(44, Ics, Line, Tlen, _, _) ->
    {45,Tlen,Ics,Line};
yystate(43, [114|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 48, Tlen);
yystate(43, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,43};
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 47, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(42, Ics, Line, Tlen+1, 47, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(42, Ics, Line, Tlen+1, 47, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(42, Ics, Line, Tlen+1, 47, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {47,Tlen,Ics,Line,42};
yystate(41, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line};
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,40};
yystate(39, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line+1, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,39};
yystate(38, [43|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 10, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,38};
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 55 ->
    yystate(37, Ics, Line, Tlen+1, 19, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,37};
yystate(36, [59|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 51, Tlen);
yystate(36, [35|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 51, Tlen);
yystate(36, [33|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 51, Tlen);
yystate(36, [34|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 51, Tlen);
yystate(36, [32|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 51, Tlen);
yystate(36, [13|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 51, Tlen);
yystate(36, [11|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 51, Tlen);
yystate(36, [12|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 51, Tlen);
yystate(36, [10|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line+1, Tlen+1, 51, Tlen);
yystate(36, [9|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 51, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(0, Ics, Line, Tlen+1, 51, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(0, Ics, Line, Tlen+1, 51, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 58 ->
    yystate(0, Ics, Line, Tlen+1, 51, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 60 ->
    yystate(0, Ics, Line, Tlen+1, 51, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {51,Tlen,Ics,Line,36};
yystate(35, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,35};
yystate(34, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,34};
yystate(33, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(32, [116|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 48, Tlen);
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,32};
yystate(31, Ics, Line, Tlen, _, _) ->
    {43,Tlen,Ics,Line};
yystate(30, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line};
yystate(29, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(29, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,29};
yystate(28, [59|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 51, Tlen);
yystate(28, [35|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 51, Tlen);
yystate(28, [33|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 51, Tlen);
yystate(28, [34|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 51, Tlen);
yystate(28, [32|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 51, Tlen);
yystate(28, [13|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 51, Tlen);
yystate(28, [11|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 51, Tlen);
yystate(28, [12|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 51, Tlen);
yystate(28, [10|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line+1, Tlen+1, 51, Tlen);
yystate(28, [9|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 51, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 8 ->
    yystate(20, Ics, Line, Tlen+1, 51, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 31 ->
    yystate(20, Ics, Line, Tlen+1, 51, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 36, C =< 58 ->
    yystate(20, Ics, Line, Tlen+1, 51, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 60 ->
    yystate(20, Ics, Line, Tlen+1, 51, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {51,Tlen,Ics,Line,28};
yystate(27, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,27};
yystate(26, [95|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 49, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(26, Ics, Line, Tlen+1, 49, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(26, Ics, Line, Tlen+1, 49, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(26, Ics, Line, Tlen+1, 49, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {49,Tlen,Ics,Line,26};
yystate(25, [91|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 14, Tlen);
yystate(25, [61|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 14, Tlen);
yystate(25, [60|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 14, Tlen);
yystate(25, [45|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 14, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,25};
yystate(24, [111|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 48, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,24};
yystate(23, [92|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 43, Tlen);
yystate(23, [34|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 43, Tlen);
yystate(23, [10|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line+1, Tlen+1, 43, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(39, Ics, Line, Tlen+1, 43, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(39, Ics, Line, Tlen+1, 43, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(39, Ics, Line, Tlen+1, 43, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(39, Ics, Line, Tlen+1, 43, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {43,Tlen,Ics,Line,23};
yystate(22, Ics, Line, Tlen, _, _) ->
    {40,Tlen,Ics,Line};
yystate(21, [48|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 18, Tlen);
yystate(21, [49|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 18, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,21};
yystate(20, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line+1, Tlen+1, Action, Alen);
yystate(20, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 8 ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 31 ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 36, C =< 58 ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 60 ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(20, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,20};
yystate(19, [114|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 48, Tlen);
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,19};
yystate(18, Ics, Line, Tlen, _, _) ->
    {54,Tlen,Ics,Line};
yystate(17, [47|Ics], Line, Tlen, _, _) ->
    yystate(96, Ics, Line, Tlen+1, 11, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,17};
yystate(16, [114|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 8, Tlen);
yystate(16, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 8, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 8, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 8, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(27, Ics, Line, Tlen+1, 8, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 8, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,16};
yystate(15, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line+1, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,15};
yystate(14, [62|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 10, Tlen);
yystate(14, [45|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 10, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,14};
yystate(13, Ics, Line, Tlen, _, _) ->
    {42,Tlen,Ics,Line};
yystate(12, [114|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 48, Tlen);
yystate(12, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,12};
yystate(11, [117|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 48, Tlen);
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,11};
yystate(10, [62|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 14, Tlen);
yystate(10, [61|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 14, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,10};
yystate(9, [46|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 39, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {39,Tlen,Ics,Line,9};
yystate(8, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line+1, Tlen+1, Action, Alen);
yystate(8, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 8 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 31 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 36, C =< 58 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, [C|Ics], Line, Tlen, Action, Alen) when C >= 60 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(8, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,8};
yystate(7, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line+1, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(7, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,7};
yystate(6, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line};
yystate(5, [62|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, [61|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 12, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,5};
yystate(4, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 5, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 5, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 5, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 5, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,4};
yystate(3, [101|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 48, Tlen);
yystate(3, [95|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 64, C =< 90 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(27, Ics, Line, Tlen+1, 48, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line,3};
yystate(2, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(1, [46|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 38, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,1};
yystate(0, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line+1, Tlen+1, Action, Alen);
yystate(0, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 8 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 31 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 36, C =< 58 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 60 ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars, TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_21(TokenChars, TokenLine);
yyaction(22, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars, TokenLine);
yyaction(23, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars, TokenLine);
yyaction(24, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars, TokenLine);
yyaction(25, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_25(TokenChars, TokenLine);
yyaction(26, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars, TokenLine);
yyaction(27, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_27(TokenChars, TokenLine);
yyaction(28, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_28(TokenChars, TokenLine);
yyaction(29, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_29(TokenChars, TokenLine);
yyaction(30, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_30(TokenChars, TokenLine);
yyaction(31, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_31(TokenChars, TokenLine);
yyaction(32, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_32(TokenChars, TokenLine);
yyaction(33, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_33(TokenChars, TokenLine);
yyaction(34, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_34(TokenChars, TokenLine);
yyaction(35, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_35(TokenChars, TokenLine);
yyaction(36, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_36(TokenChars, TokenLine);
yyaction(37, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_37(TokenChars, TokenLine);
yyaction(38, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_38(TokenChars, TokenLine);
yyaction(39, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_39(TokenChars, TokenLine);
yyaction(40, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_40(TokenChars, TokenLine);
yyaction(41, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_41(TokenChars, TokenLine);
yyaction(42, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_42(TokenChars, TokenLine);
yyaction(43, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_43(TokenChars, TokenLen, TokenLine);
yyaction(44, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_44(TokenChars, TokenLine);
yyaction(45, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_45(TokenChars, TokenLine);
yyaction(46, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_46(TokenChars, TokenLine);
yyaction(47, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_47(TokenChars, TokenLine);
yyaction(48, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_48(TokenChars, TokenLine);
yyaction(49, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_49(TokenChars, TokenLine);
yyaction(50, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_50(TokenChars, TokenLine);
yyaction(51, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_51(TokenChars, TokenLine);
yyaction(52, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_52(TokenChars, TokenLine);
yyaction(53, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_53(TokenChars, TokenLine);
yyaction(54, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_54(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("src/test.xrl", 74).
yyaction_0(TokenChars, TokenLine) ->
     make_token (shift_op, TokenLine, TokenChars) .

-compile({inline,yyaction_1/2}).
-file("src/test.xrl", 75).
yyaction_1(TokenChars, TokenLine) ->
     make_token (bin_not, TokenLine, TokenChars) .

-compile({inline,yyaction_2/2}).
-file("src/test.xrl", 76).
yyaction_2(TokenChars, TokenLine) ->
     make_token (and_op, TokenLine, TokenChars) .

-compile({inline,yyaction_3/2}).
-file("src/test.xrl", 77).
yyaction_3(TokenChars, TokenLine) ->
     make_token (or_op, TokenLine, TokenChars) .

-compile({inline,yyaction_4/2}).
-file("src/test.xrl", 80).
yyaction_4(TokenChars, TokenLine) ->
     make_token (bool_not, TokenLine, TokenChars) .

-compile({inline,yyaction_5/2}).
-file("src/test.xrl", 81).
yyaction_5(TokenChars, TokenLine) ->
     make_token (boolean, TokenLine, TokenChars) .

-compile({inline,yyaction_6/2}).
-file("src/test.xrl", 82).
yyaction_6(TokenChars, TokenLine) ->
     make_token (bool_andalso_op, TokenLine, TokenChars) .

-compile({inline,yyaction_7/2}).
-file("src/test.xrl", 83).
yyaction_7(TokenChars, TokenLine) ->
     make_token (bool_and_op, TokenLine, TokenChars) .

-compile({inline,yyaction_8/2}).
-file("src/test.xrl", 84).
yyaction_8(TokenChars, TokenLine) ->
     make_token (bool_orelse_op, TokenLine, TokenChars) .

-compile({inline,yyaction_9/2}).
-file("src/test.xrl", 85).
yyaction_9(TokenChars, TokenLine) ->
     make_token (bool_or_op, TokenLine, TokenChars) .

-compile({inline,yyaction_10/2}).
-file("src/test.xrl", 88).
yyaction_10(TokenChars, TokenLine) ->
     make_token (add_op, TokenLine, TokenChars) .

-compile({inline,yyaction_11/2}).
-file("src/test.xrl", 89).
yyaction_11(TokenChars, TokenLine) ->
     make_token (mul_op, TokenLine, TokenChars) .

-compile({inline,yyaction_12/2}).
-file("src/test.xrl", 90).
yyaction_12(TokenChars, TokenLine) ->
     make_token (match, TokenLine, TokenChars) .

-compile({inline,yyaction_13/2}).
-file("src/test.xrl", 91).
yyaction_13(TokenChars, TokenLine) ->
     make_token (set, TokenLine, TokenChars) .

-compile({inline,yyaction_14/2}).
-file("src/test.xrl", 93).
yyaction_14(TokenChars, TokenLine) ->
     make_token (comp_op, TokenLine, TokenChars) .

-compile({inline,yyaction_15/2}).
-file("src/test.xrl", 96).
yyaction_15(TokenChars, TokenLine) ->
     make_token (concat_op, TokenLine, TokenChars) .

-compile({inline,yyaction_16/2}).
-file("src/test.xrl", 99).
yyaction_16(TokenChars, TokenLine) ->
     make_token (float, TokenLine, TokenChars, fun erlang : list_to_float / 1) .

-compile({inline,yyaction_17/2}).
-file("src/test.xrl", 100).
yyaction_17(TokenChars, TokenLine) ->
     make_token (integer, TokenLine, TokenChars, fun erlang : list_to_integer / 1) .

-compile({inline,yyaction_18/2}).
-file("src/test.xrl", 101).
yyaction_18(TokenChars, TokenLine) ->
     make_token (integer, TokenLine, TokenChars, fun bin_to_integer / 1) .

-compile({inline,yyaction_19/2}).
-file("src/test.xrl", 102).
yyaction_19(TokenChars, TokenLine) ->
     make_token (integer, TokenLine, TokenChars, fun oct_to_integer / 1) .

-compile({inline,yyaction_20/2}).
-file("src/test.xrl", 103).
yyaction_20(TokenChars, TokenLine) ->
     make_token (integer, TokenLine, TokenChars, fun hex_to_integer / 1) .

-compile({inline,yyaction_21/2}).
-file("src/test.xrl", 106).
yyaction_21(TokenChars, TokenLine) ->
     make_token (open_meta_block, TokenLine, TokenChars) .

-compile({inline,yyaction_22/2}).
-file("src/test.xrl", 107).
yyaction_22(TokenChars, TokenLine) ->
     make_token (open_meta_oxford, TokenLine, TokenChars) .

-compile({inline,yyaction_23/2}).
-file("src/test.xrl", 108).
yyaction_23(TokenChars, TokenLine) ->
     make_token (open_bin, TokenLine, TokenChars) .

-compile({inline,yyaction_24/2}).
-file("src/test.xrl", 109).
yyaction_24(TokenChars, TokenLine) ->
     make_token (close_bin, TokenLine, TokenChars) .

-compile({inline,yyaction_25/2}).
-file("src/test.xrl", 110).
yyaction_25(TokenChars, TokenLine) ->
     make_token (open, TokenLine, TokenChars) .

-compile({inline,yyaction_26/2}).
-file("src/test.xrl", 111).
yyaction_26(TokenChars, TokenLine) ->
     make_token (close, TokenLine, TokenChars) .

-compile({inline,yyaction_27/2}).
-file("src/test.xrl", 112).
yyaction_27(TokenChars, TokenLine) ->
     make_token (open_block, TokenLine, TokenChars) .

-compile({inline,yyaction_28/2}).
-file("src/test.xrl", 113).
yyaction_28(TokenChars, TokenLine) ->
     make_token (close_block, TokenLine, TokenChars) .

-compile({inline,yyaction_29/2}).
-file("src/test.xrl", 114).
yyaction_29(TokenChars, TokenLine) ->
     make_token (open_list, TokenLine, TokenChars) .

-compile({inline,yyaction_30/2}).
-file("src/test.xrl", 115).
yyaction_30(TokenChars, TokenLine) ->
     make_token (close_list, TokenLine, TokenChars) .

-compile({inline,yyaction_31/2}).
-file("src/test.xrl", 116).
yyaction_31(TokenChars, TokenLine) ->
     make_token (open_oxford, TokenLine, TokenChars) .

-compile({inline,yyaction_32/2}).
-file("src/test.xrl", 117).
yyaction_32(TokenChars, TokenLine) ->
     make_token (close_oxford, TokenLine, TokenChars) .

-compile({inline,yyaction_33/2}).
-file("src/test.xrl", 119).
yyaction_33(TokenChars, TokenLine) ->
     make_token (sep, TokenLine, TokenChars) .

-compile({inline,yyaction_34/2}).
-file("src/test.xrl", 120).
yyaction_34(TokenChars, TokenLine) ->
     make_token (send_op, TokenLine, TokenChars) .

-compile({inline,yyaction_35/2}).
-file("src/test.xrl", 121).
yyaction_35(TokenChars, TokenLine) ->
     make_token (split_def_op, TokenLine, TokenChars) .

-compile({inline,yyaction_36/2}).
-file("src/test.xrl", 122).
yyaction_36(TokenChars, TokenLine) ->
     make_token (split_op, TokenLine, TokenChars) .

-compile({inline,yyaction_37/2}).
-file("src/test.xrl", 123).
yyaction_37(TokenChars, TokenLine) ->
     make_token (dotdotdot, TokenLine, TokenChars) .

-compile({inline,yyaction_38/2}).
-file("src/test.xrl", 124).
yyaction_38(TokenChars, TokenLine) ->
     make_token (dotdot, TokenLine, TokenChars) .

-compile({inline,yyaction_39/2}).
-file("src/test.xrl", 125).
yyaction_39(TokenChars, TokenLine) ->
     make_token (dot, TokenLine, TokenChars) .

-compile({inline,yyaction_40/2}).
-file("src/test.xrl", 126).
yyaction_40(TokenChars, TokenLine) ->
     make_token (arrow, TokenLine, TokenChars) .

-compile({inline,yyaction_41/2}).
-file("src/test.xrl", 127).
yyaction_41(TokenChars, TokenLine) ->
     make_token (larrow, TokenLine, TokenChars) .

-compile({inline,yyaction_42/2}).
-file("src/test.xrl", 128).
yyaction_42(TokenChars, TokenLine) ->
     make_token (fatarrow, TokenLine, TokenChars) .

-compile({inline,yyaction_43/3}).
-file("src/test.xrl", 131).
yyaction_43(TokenChars, TokenLen, TokenLine) ->
     build_string (string, TokenChars, TokenLine, TokenLen) .

-compile({inline,yyaction_44/2}).
-file("src/test.xrl", 132).
yyaction_44(TokenChars, TokenLine) ->
     make_token (macrovar, TokenLine, tl (TokenChars)) .

-compile({inline,yyaction_45/2}).
-file("src/test.xrl", 133).
yyaction_45(TokenChars, TokenLine) ->
     make_token (char, TokenLine, TokenChars, fun (Char) -> list_to_charnum (Char, TokenLine) end) .

-compile({inline,yyaction_46/2}).
-file("src/test.xrl", 136).
yyaction_46(TokenChars, TokenLine) ->
     make_token (var, TokenLine, TokenChars) .

-compile({inline,yyaction_47/2}).
-file("src/test.xrl", 137).
yyaction_47(TokenChars, TokenLine) ->
     make_token (modvar, TokenLine, tl (TokenChars)) .

-compile({inline,yyaction_48/2}).
-file("src/test.xrl", 138).
yyaction_48(TokenChars, TokenLine) ->
     { token, atom_or_identifier (TokenChars, TokenLine) } .

-compile({inline,yyaction_49/2}).
-file("src/test.xrl", 139).
yyaction_49(TokenChars, TokenLine) ->
     make_token (gattr, TokenLine, tl (tl (TokenChars))) .

-compile({inline,yyaction_50/2}).
-file("src/test.xrl", 140).
yyaction_50(TokenChars, TokenLine) ->
     make_token (attr, TokenLine, tl (TokenChars)) .

-compile({inline,yyaction_51/2}).
-file("src/test.xrl", 143).
yyaction_51(TokenChars, TokenLine) ->
     make_token (endl, TokenLine, endls (TokenChars)) .

-compile({inline,yyaction_52/2}).
-file("src/test.xrl", 144).
yyaction_52(TokenChars, TokenLine) ->
     make_token (white, TokenLine, length (TokenChars)) .

-compile({inline,yyaction_53/2}).
-file("src/test.xrl", 145).
yyaction_53(TokenChars, TokenLine) ->
     make_token (tab, TokenLine, length (TokenChars)) .

-compile({inline,yyaction_54/2}).
-file("src/test.xrl", 148).
yyaction_54(TokenChars, TokenLine) ->
     make_token (question, TokenLine, TokenChars) .

-file("/usr/local/lib/erlang/lib/parsetools-2.0.9/include/leexinc.hrl", 282).
